hyperskill_project:
  id: 54
  ide_files: https://cogniterra.org/media/attachments/lesson/23037/additional_files.json
  is_template_based: false
  use_ide: true
update_date: "Tue, 29 Oct 2024 07:22:23 UTC"
stages:
  - id: 294
    step: 5436
    is_completed: true
  - id: 295
    step: 5437
    is_completed: true
  - id: 296
    step: 5438
    is_completed: true
  - id: 298
    step: 5440
    is_completed: true
  - id: 299
    step: 5441
    is_completed: true
topics:
  0:
    - title: "Write, compile, and run"
      theory_id: 3739
    - title: Introduction to Java
      theory_id: 38627
    - title: "Basic literals: numbers, strings and characters"
      theory_id: 3522
    - title: Writing first program
      theory_id: 3521
    - title: Printing data
      theory_id: 3749
    - title: Types and variables
      theory_id: 3518
    - title: Comments
      theory_id: 3520
    - title: Reading user's input with Scanner
      theory_id: 9055
    - title: Coding style conventions
      theory_id: 12411
    - title: Naming variables
      theory_id: 3513
    - title: Arithmetic operations
      theory_id: 3519
    - title: Integer types and operations
      theory_id: 3565
    - title: Increment and decrement
      theory_id: 5008
    - title: Data types and their sizes
      theory_id: 3532
    - title: Type casting
      theory_id: 3510
    - title: Calling methods
      theory_id: 10973
    - title: Floating-point types
      theory_id: 3517
    - title: Boolean type and operations. True and false
      theory_id: 3516
    - title: Comparing values. Relational operators
      theory_id: 3512
    - title: Conditional statement
      theory_id: 3503
    - title: One-line condition with ternary operator
      theory_id: 3506
    - title: While and do-while loops
      theory_id: 3498
    - title: For loop
      theory_id: 3505
    - title: Break and continue. Branching
      theory_id: 3507
    - title: Declaring methods
      theory_id: 10982
    - title: Method "main"
      theory_id: 3489
    - title: "Multiple conditions: switch"
      theory_id: 3504
    - title: Functional decomposition
      theory_id: 10570
    - title: Primitive and reference types
      theory_id: 5035
    - title: Array
      theory_id: 3511
    - title: Arrays as parameters
      theory_id: 3594
    - title: Characters
      theory_id: 3514
    - title: String
      theory_id: 3523
    - title: Constants. Final variables
      theory_id: 7427
    - title: IntelliJ IDEA
      theory_id: 37202
    - title: Random class
      theory_id: 4910
    - title: Defining classes
      theory_id: 3618
    - title: Instance methods
      theory_id: 3495
    - title: Initializing new instances. Constructor
      theory_id: 3535
    - title: Objects and their properties
      theory_id: 4727
    - title: Static members
      theory_id: 3534
  1:
    - title: Overloading
      theory_id: 3525
    - title: Iterating over arrays
      theory_id: 3602
    - title: Errors in programs
      theory_id: 3536
    - title: First glance at exceptions
      theory_id: 3497
    - title: Hierarchy of exceptions
      theory_id: 3570
    - title: Exception handling
      theory_id: 3552
    - title: What are bugs
      theory_id: 5504
    - title: Multidimensional array
      theory_id: 1933
    - title: Introduction to logging
      theory_id: 5538
    - title: Debugging techniques
      theory_id: 13775
    - title: Grouping classes with packages
      theory_id: 3621
    - title: Access modifiers
      theory_id: 3589
    - title: Getters and setters
      theory_id: 3599
    - title: Inheritance
      theory_id: 3583
    - title: Multiple constructors
      theory_id: 3538
    - title: Keyword "super"
      theory_id: 3588
  2:
    - title: Immutability
      theory_id: 7929
    - title: NullPointerException
      theory_id: 1945
    - title: What is object-oriented programming
      theory_id: 3614
    - title: Introduction to generic programming
      theory_id: 3492
    - title: Protected modifier
      theory_id: 6692
    - title: Referencing subclass objects
      theory_id: 3585
    - title: Adding annotations
      theory_id: 3622
    - title: Method overriding
      theory_id: 3572
    - title: Polymorphism
      theory_id: 3587
    - title: Declaring functionality with interfaces
      theory_id: 3615
    - title: Anonymous class
      theory_id: 11896
    - title: Abstract class
      theory_id: 3597
    - title: Initialization blocks
      theory_id: 3533
    - title: Anonymous classes properties
      theory_id: 3564
    - title: Wrapping classes. Boxing
      theory_id: 3595
  3:
    - title: Introduction to UI/UX
      theory_id: 14603
    - title: The basic window in Swing
      theory_id: 5514
    - title: Layout grids
      theory_id: 14922
    - title: Interface elements
      theory_id: 15253
    - title: Model-View-Controller (MVC) in Swing
      theory_id: 19656
    - title: Layout managers
      theory_id: 6824
    - title: Introduction to Swing components
      theory_id: 6295
    - title: The Graphics class
      theory_id: 11930
    - title: Libraries
      theory_id: 8504
    - title: "Synchronous, asynchronous, parallel"
      theory_id: 9332
    - title: Processes and threads
      theory_id: 9420
    - title: Introduction to software architecture
      theory_id: 15368
    - title: Lambda expressions
      theory_id: 11635
    - title: Method references
      theory_id: 3620
    - title: Functional interfaces
      theory_id: 11636
    - title: Threads as objects
      theory_id: 4875
    - title: Custom threads
      theory_id: 4876
    - title: Thread management
      theory_id: 3619
    - title: Exceptions in threads
      theory_id: 4882
    - title: Interruptions
      theory_id: 4881
    - title: States of a thread
      theory_id: 4883
    - title: MVC
      theory_id: 17197
    - title: Default methods
      theory_id: 11354
